### ISSUE TITLE
request for a TrueCommand LXC deployment for use on ProxMox

### ISSUE THREAD

**Issue by commandline-be** [iXsystems/TrueCommand-install#1]
Hey

Just a random request for an LXC template to deploy TrueCommand. 

Why you ask ? 

As to avoid using docker and still have a container running.

https://pve.proxmox.com/wiki/Linux_Container

Thanks

JL

**Comment by william-gr** [comment]
Hello, please put in a feature request in https://jira.ixsystems.com/
